### ISSUE TITLE
Boxplot widths not scaling well with figwidth

### ISSUE THREAD

**Issue by elide-b** [elide-b/lastplot#2]
aec03fa scales some of the plots with the amount of boxplots in the figure, but this causes the boxplots to become more narrow:

![image](https://github.com/user-attachments/assets/2e0e6f1e-7159-4564-933f-b765fc53147b)

@Helveg

**Comment by Helveg** [comment]
The next commit (6b77cd2bff8312f8bf3c3c1ffe7127a9dae7b2f4) undoes this change, so this bug no longer exists.

Feel free to tag me again if something similar occurs again.

**Comment by Helveg** [comment]
Ok, so there was another case with `n_bars=1` that I see you fixed now
